name = "Reversi"
uuid = "8f7655e2-04a7-45c2-9cb3-16b1b80822ae"
version = "0.3.2"
authors = ["sota <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
ReversiGLMakieExt = "GLMakie"

[compat]
GLMakie = "0.13"
TOML = "1.0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
